[CELEBORN-2300] Change the default value of celeborn.port.maxRetries from 1 to 16
### What changes were proposed in this pull request?

### Why are the changes needed?

Align with spark.port.maxRetries, default to 16 retries.

```java
ERROR Executor: Exception in task 1153.0 in stage 11763.0 (TID 516674)
java.lang.RuntimeException: java.net.BindException: Address already in use: Service 'ShuffleClient' failed after 1 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'ShuffleClient' to the correct binding address.
	at org.apache.spark.shuffle.celeborn.SparkShuffleManager.getWriter(SparkShuffleManager.java:310)
```

### Does this PR resolve a correctness bug?
No

### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
GHA

Closes #3648 from cxzl25/CELEBORN-2300.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: SteNicholas <programgeek@163.com>